import './global.css';
import { Toaster } from 'sonner';
import '@mantine/core/styles.css';
import '@mantine/dates/styles.css';
import { MantineProvider } from '@mantine/core';
import RatingModal from '@/components/RatingModal';

export const metadata = {
  title: 'Welcome to ',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <MantineProvider>
          {children}
          <RatingModal />
          <Toaster richColors position="bottom-right" />
        </MantineProvider>
      </body>
    </html>
  );
}
